### ISSUE TITLE
Add feed for RubyGems

### ISSUE THREAD

**Issue by dlorenc** [ossf/package-feeds#14]
cc @jordan-wright

**Comment by Qinusty** [comment]
Given the state of https://github.com/ossf/package-feeds/blob/main/feeds/rubygems/rubygems.go. I assume this can be closed?

**Comment by naveensrinivasan** [comment]
> Given the state of https://github.com/ossf/package-feeds/blob/main/feeds/rubygems/rubygems.go. I assume this can be closed?

Yes, Thanks.
