### ISSUE TITLE
Add a go module feed

### ISSUE THREAD

**Issue by dlorenc** [ossf/package-feeds#29]
Go doesn't allow code execution at download time, but it would still be useful to add a package feed for other use cases.

Docs here: https://proxy.golang.org/
Feed here: https://index.golang.org/index

**Comment by steiza** [comment]
I'll take a crack at this

**Comment by tom--pollard** [comment]
This can be closed now with https://github.com/ossf/package-feeds/pull/55 landing? :smiley:

**Comment by naveensrinivasan** [comment]
Thanks!
