### ISSUE TITLE
Including an HTTP Publisher

### ISSUE THREAD

**Issue by R9295** [ossf/package-feeds#386]
Hello all,

Any thoughts on including a HTTP publisher that sends a HTTP POST request to a configurable address? 
It is trivial to implement and if ya'll would like to introduce such functionality, I would love to contribute. 

Regards,
Aarnav

**Comment by calebbrown** [comment]
Hi Aarnav,

You're definitely welcome to implement this feature. Web-hooks are a common approach (apart from pubsub) for receiving notifications when events occur.

Did you have in mind an approach for handling failures?


Caleb

**Comment by R9295** [comment]
No I do not, but I imagine we can use the same strategies as the other publishers that work over the network?

**Comment by yrobla** [comment]
I created https://github.com/ossf/package-feeds/pull/457
