### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by lukehinds** [ossf/package-feeds#428]
Is there an appetite to include support for ingestion of java (maven) packages? 

We (stacklok) are happy to develop the needed code.

**Comment by calebbrown** [comment]
We are happy to accept code to support ingesting Java (Maven) packages.

I suspect you would initially be the only user of the feed, but that isn't really a problem.

Package Analysis doesn't have immediate plans to add Java support.

Was there a particular Maven repository you were interested in supporting (e.g. Maven Central)?

**Comment by yrobla** [comment]
Hi! So I was basically thinking in using Sonatype API: https://help.sonatype.com/en/components-api.html
And yep, target repository could likely be Maven Central. There is control there to sort by published date, so the feed could be based on that.

**Comment by calebbrown** [comment]
That sounds fair.

We likely want a way to distinguish Maven repository in the feed, either by calling the feed "maven central" itself, or adding a field to indicate the repository.

**Comment by calebbrown** [comment]
Maven central support is now implemented, please reopen or create a new issue if there is any outstanding work.

Thanks for the contribution!
