### ISSUE TITLE
Move to Go 1.16

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/package-feeds#63]
Migrate to go `1.16`

**Comment by phumberdroz** [comment]
closed via a083a4e2e90bded4e429a5ebaf604d6629bfdbf1 ?

**Comment by naveensrinivasan** [comment]
> closed via [a083a4e](https://github.com/ossf/package-feeds/commit/a083a4e2e90bded4e429a5ebaf604d6629bfdbf1) ?

We still have to test it with 1.16 explicitly.

**Comment by tom--pollard** [comment]
As 1.16.2 has now also merged in, can we assume testing has been complete?

**Comment by naveensrinivasan** [comment]
Yes. Thanks
